# Generated by Django 5.1.2 on 2025-01-30 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_Id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(choices=[('RobbyRoss', 'Majaba')], max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('court_Id', models.AutoField(primary_key=True, serialize=False)),
                ('courtStatus', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('Barangay San Nicolas 3 Court', 'Barangay San Nicolas 3 Phase 1'), ('Barangay Molino 3 Court', 'Barangay Molino 3 Phase 2')], max_length=100)),
                ('date', models.DateField()),
                ('available', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('payment_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.court')),
            ],
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.court')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.feedback')),
                ('reservation_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reservation')),
            ],
        ),
    ]
